server:
  port: 8081

spring:
  application:
    name: lms
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/lms_db
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
